### ISSUE TITLE
Bug: Registration & Login page needs responsiveness

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#165]
### Description

When the registration page & the login page is being opened with smaller or larger screens, they are taking up spaces in a distorted way. 

### Proposed Solution

The UI of the registration and login page should be clean and pleasant after opening in different screen sizes. 

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by Sky-De** [comment]
@ItsRoy69 Hi, I would like to help you address this issue. Could you please assign the project to me? Thank you.

**Comment by ItsRoy69** [comment]
Go for it

**Comment by Sky-De** [comment]
@ItsRoy69 hey again, thanks for the assignment, there is something I want to share with you before I modify the code

Current UI of the register page 
![chrome-capture-2024-1-1 (1)](https://github.com/WikiPortal/DoodleCollab/assets/79264045/476a3540-d5ee-4c40-a81f-edba349e704e)


1. because of using position fixed you had to add margin-top to all your pages ( it can be fixed using sticky)
2. Can I remove the image on the registration page for mobile devices ( or even use it as bg )?
3. Can I reduce the gaps to make the content fit on the desktop without the need to scroll?
4. Can I eliminate the extra space on the footer?
5. Can I reduce the size of the form title?

Kindly inform me about the details. This will enable me to initiate the fixing process at the earliest.

**Comment by ItsRoy69** [comment]
1. Use sticky for the image
2. Better as it'll be clean then
3. No will be prioritised but if the form looks clean then do
4. Yes
5. Same as 3

**Comment by Sky-De** [comment]
@ItsRoy69 Hi again, I have a question about this project, I created issue #174, and I fixed that and created a PR, but I could not assign that to myself also no one responded to that PR, what can I do about that?
